#!/usr/bin/env python3

import acc

import os
import shutil
import subprocess
import sys

class IO:
    def __init__(self):
        self.stdout = sys.stdout
        self.stderr = sys.stderr
        self.chdir = os.chdir
        self.isdir = os.path.isdir
        self.dirname = os.path.dirname
        self.abspath = os.path.abspath
        self.islink = os.path.islink
        self.exists = os.path.exists
        self.which = shutil.which
        self.mkdir = os.mkdir
        self.run = subprocess.run
        self.join = os.path.join
        self.makedirs = os.makedirs

if __name__ == "__main__":
    program_name = "acc"
    args = sys.argv[1:]
    sys.exit(acc.command_line(program_name, args, IO()))
